---
services:
  pigpio:
    # cap_add:
    #   - SYS_RAWIO  # needed for GPIO access
    container_name: pigpio
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    devices:
      - /dev/gpiochip0
    environment:
      # PIGPIO_PORT: ${PIGPIO_PORT:-8888}
      # PIGPIO_ARGS: ${PIGPIO_ARGS:- -g}
      TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       nc -z -i 1 -w 1 localhost ${PIGPIO_PORT:-8888} || exit 1
    #   timeout: 10s
    hostname: pigpio
    image: woahbase/alpine-pigpio:${PIGPIO_TAG:-latest}
    network_mode: bridge
    # privileged: true  # run with all privileges if not working otherwise
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${PIGPIO_PORT:-8888}
        target: 8888
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
