---
services:
  ttrss:
    container_name: ttrss
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    #   postgresql:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4096M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      # TZ: ${TZ}

      # for updating
      # TTRSSUPDATE: 1

      TTRSS_DB_TYPE: pgsql
      TTRSS_DB_HOST: your.postgres.local
      TTRSS_DB_PORT: 5432
      TTRSS_DB_USER: ttrss
      TTRSS_DB_PASS: insecurebydefault
      TTRSS_DB_NAME: ttrss

      # ADMIN_USER_PASS: "insecurebydefault"
      # ADMIN_USER_ACCESS_LEVEL: "-2"

      # AUTO_CREATE_USER: "feeduser"
      # AUTO_CREATE_USER_PASS: "insecurebydefaultuser"
      # AUTO_CREATE_USER_ENABLE_API: "true"
      # AUTO_CREATE_USER_ACCESS_LEVEL: "0"

      # NO_STARTUP_SCHEMA_UPDATES: 1

      # NO_STARTUP_PLUGIN_UPDATES: 1
      # git required for local plugin updates
      # S6_NEEDED_PACKAGES: "git"

    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       curl -f http://localhost:80/ttrss/public.php?op=healthcheck || exit 1
    #   timeout: 10s
    hostname: ttrss
    image: woahbase/alpine-ttrss:${TTRSS_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${TTRSS_PORT:-80}
        target: 80
      # # optionally with https
      # # requires certificates, either provided, or self-signed ones generated
      # - protocol: tcp
      #   host_ip: 0.0.0.0
      #   published: ${TTRSS_PORT:-443}
      #   target: 443
    volumes:
      # - type: bind
      #   source: ${CERTIFICATE_DIR:?err}/ttrss
      #   target: /config/keys
      #   bind:
      #     create_host_path: true
      - type: bind
        source: ${TTRSS_DIR:?err}/config
        target: /config
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${TTRSS_DIR:?err}/configs/config.php
      #   target: /config/www/ttrss/config.php
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
