---
services:
  wallabag:
    container_name: wallabag
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       curl -f http://localhost:80/ || exit 1
    #   timeout: 10s
    hostname: wallabag
    image: woahbase/alpine-wallabag:${WALLABAG_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${WALLABAG_PORT:-80}
        target: 80
    volumes:
      # - type: bind
      #   source: ${CERTIFICATE_DIR:?err}/generated
      #   target: /config/keys
      #   bind:
      #     create_host_path: true
      - type: bind
        source: ${WALLABAG_DIR:?err}/images
        target: /config/www/wallabag/web/assets/images
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${WALLABAG_DIR:?err}/configs/parameters.yml
      #   target: /defaults/parameters.yml
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
