---
services:
  kapacitor:
    container_name: kapacitor
    # depends_on:
    #   influxdb:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
      # KAPACITOR_AS_ROOT: 1  # set to run as root, default as user alpine
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget -q -T 2 --no-check-certificate -O -
    #       http://localhost:9092/kapacitor/v1/ping
    #       | grep -q "HTTP/1.1 204 No Content"
    #       || exit 1
    #   timeout: 10s
    hostname: kapacitor
    image: woahbase/alpine-kapacitor:${KAPACITOR_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: '${KAPACITOR_PORT:-9092}'
        target: 9092
    volumes:
      - type: bind
        source: ${KAPACITOR_DIR:?err}
        target: /var/lib/kapacitor
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${KAPACITOR_DIR:?err}/kapacitor.conf
      #   target: /etc/kapacitor/kapacitor.conf
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
