---
services:
  navidrome:
    container_name: navidrome
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 3
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget -q -T '2' -O /dev/null http://localhost:${ND_PORT:-4533}${ND_BASEURL:-/navidrome}/ping || exit 1
    #   timeout: 10s
    hostname: navidrome
    image: woahbase/alpine-navidrome:${NAVIDROME_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${ND_PORT:-4533}
        target: ${ND_PORT:-4533}
    volumes:
      - type: bind
        source: ${NAVIDROME_DIR:?err}
        target: /data
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${NAVIDROME_DIR:?err}/configs/navidrome.toml
      #   target: /data/navidrome.toml
      #   bind:
      #     create_host_path: false
      - type: bind
        source: ${MUSICDIR:?err}
        target: /music
        bind:
          create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
