---
services:
  nfs:
    # cap_add:
    #   - SYS_ADMIN
    #   - SETPCAP
    container_name: nfs
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      # TZ: ${TZ}
    hostname: nfs
    image: woahbase/alpine-nfs:${NFS_TAG:-latest}
    network_mode: host
    # ports:
    # # for nfsv4
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 111, target: 111}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 111, target: 111}
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 2049, target: 2049}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 2049, target: 2049}
    # # for nfs v3/v2, ports for mountd/statd
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 32765, target: 32765}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 32765, target: 32765}
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 32766, target: 32766}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 32766, target: 32766}
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 32767, target: 32767}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 32767, target: 32767}
    #   - {protocol: "tcp", host_ip: "0.0.0.0", published: 32768, target: 32768}
    #   - {protocol: "udp", host_ip: "0.0.0.0", published: 32768, target: 32768}
    # # ports may need to be whitelisted in firewall
    # # to allow access from network
    privileged: true
    volumes:
      - type: bind
        source: ${NFS_ROOT:?err}/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: ${NFS_ROOT:?err}/configs/exports
        target: /etc/exports
        bind:
          create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
