---
services:
  ubooquity:
    container_name: ubooquity
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1536M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      MAXMEM: 1024
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      # TZ: ${TZ}
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget --quiet --tries=1 --no-check-certificate --spider http://localhost:2202/ubooquity/ || exit 1
    #   interval: 2m
    #   timeout: 10s
    #   retries: 5
    #   start_period: 5m
    hostname: ubooquity
    image: woahbase/alpine-ubooquity:${UBOOQUITY_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: 2202
        target: 2202
      # - protocol: tcp
      #   host_ip: 0.0.0.0
      #   published: 2203
      #   target: 2203
    volumes:
      - type: bind
        source: ${UBOOQUITY_DIR:?err}/config
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${BOOKSDIR:?err}
        target: /books
        bind:
          create_host_path: false
      # - type: bind
      #   source: ${COMICSDIR:?err}
      #   target: /comics
      #   bind:
      #     create_host_path: false
      # - type: bind
      #   source: ${FILESDIR:?err}
      #   target: /files
      #   bind:
      #     create_host_path: false
      # - type: bind
      #   source: ${UBOOQUITY_DIR:?err}/config/preferences.json
      #   target: /config/preferences.json
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
