---
services:
  kanboard:
    container_name: kanboard
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      # KANBOARD_URL: "http://your-domain.local/kanboard/"
      # KANBOARD_UPDATE: "false"
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget --quiet --tries=1 --no-check-certificate --spider "http://localhost:80/kanboard/" || exit 1
    #   timeout: 10s
    hostname: kanboard
    image: woahbase/alpine-kanboard:${KANBOARD_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${KANBOARD_PORT:-80}
        target: 80
      # # optionally with https
      # # requires certificates, either provided, or self-signed ones generated
      # - protocol: tcp
      #   host_ip: 0.0.0.0
      #   published: ${KANBOARD_HTTPS_PORT:-443}
      #   target: 443
    volumes:
      # - type: bind  # to use your own certificates with kanboard
      #   source: ${CERTIFICATE_DIR:?err}
      #   target: /config/keys
      #   bind:
      #     create_host_path: true
      # - type: bind
      #   source: ${KANBOARD_DIR:?err}/config/log
      #   target: /config/log
      #   bind:
      #     create_host_path: true
      - type: bind
        source: ${KANBOARD_DIR:?err}/data
        target: /config/www/kanboard/data
        bind:
          create_host_path: true
      - type: bind
        source: ${KANBOARD_DIR:?err}/plugins
        target: /config/www/kanboard/plugins
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${KANBOARD_DIR:?err}/config.php
      #   target: /config/www/kanboard/config.php
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
