---
services:
  influxdb:
    container_name: influxdb
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 4096M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
      INFLUXDB_REPORTING_DISABLED: true
      # INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      # INFLUXDB_ADMIN_PWD: ${INFLUXDB_ADMIN_PWD:-admin}
      # INFLUXDB_HEALTHCHECK_USER: ${INFLUXDB_HEALTHCHECK_USER:-hc}
      # INFLUXDB_HEALTHCHECK_USER_PWD: ${INFLUXDB_HEALTHCHECK_PWD:-hc}
      INFLUXDB_GRAPHITE_ENABLED: false
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       influx
    #       -username ${INFLUXDB_HEALTHCHECK_USER}
    #       -password ${INFLUXDB_HEALTHCHECK_USER_PWD}
    #       -execute 'SHOW DATABASES'
    #       || exit 1
    #     #   curl -f http://localhost:8086/metrics
    #   timeout: 10s
    hostname: influxdb
    image: woahbase/alpine-influxdb:${INFLUXDB_TAG}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: 8083
        target: 8083
      - protocol: tcp
        host_ip: 0.0.0.0
        published: 2003
        target: 2003
      - protocol: tcp
        host_ip: 0.0.0.0
        published: '${INFLUXDB_PORT:-8086}'
        target: 8086
    volumes:
      - type: bind
        source: ${INFLUXDB_DIR:?err}/data
        target: /var/lib/influxdb
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${INFLUXDB_DIR:?err}/configs/influxdb.conf
      #   target: /etc/influxdb.conf
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
