---
services:
  apcupsd:
    container_name: apcupsd
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    devices:
      - ${APCUPSD__DEVICE:-/dev/usb/hiddev0}:${APCUPSD__DEVICE:-/dev/usb/hiddev0}
    environment:
      # APCUPSD__DEVICE: ${APCUPSD__DEVICE:-/dev/usb/hiddev0}
      # APCUPSD__UPSCABLE: usb
      # APCUPSD__UPSNAME: ups0
      # APCUPSD__UPSTYPE: usb
      # APCUPSD_HEADLESS: "true"
      # APCUPSD_MONITOR_HOSTS: >-
      #   ups.local:APC UPS,
      #   test.ups.local:Test APC UPS
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       apcaccess -h localhost:3551 -p DATE || exit 1
    #     # # or
    #     # - >
    #     #   nc -z -i 1 -w 1 localhost ${APCUPSD_PORT:-3551} || exit 1
    #   timeout: 10s
    hostname: apcupsd
    image: woahbase/alpine-apcupsd:${APCUPSD_TAG:-latest}
    network_mode: bridge
    ports:
      # - protocol: tcp
      #   host_ip: 0.0.0.0
      #   published: ${APCUPSD_WEBUI_PORT:-3552}
      #   target: 80
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${APCUPSD_PORT:-3551}
        target: 3551
      - protocol: udp
        host_ip: 0.0.0.0
        published: ${APCUPSD_PORT:-3551}
        target: 3551
    volumes:
      # - type: bind
      #   source: ${APCUPSD_DIR:?err}
      #   target: /etc/apcupsd
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
