---
services:
  syncthing:
    container_name: syncthing
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget --quiet --tries=1 --no-check-certificate -O - "http://localhost:8384/rest/noauth/health" \
    #       | grep -o --color=never OK \
    #       || exit 1
    #   timeout: 10s
    hostname: syncthing
    image: woahbase/alpine-syncthing:${SYNCTHING_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${SYNCTHING_PORT_HTTP:-8384}
        target: 8384
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${SYNCTHING_PORT_QUIC:-22000}
        target: 22000
      - protocol: udp
        host_ip: 0.0.0.0
        published: ${SYNCTHING_PORT_QUIC:-22000}
        target: 22000
      - protocol: udp
        host_ip: 0.0.0.0
        published: ${SYNCTHING_PORT_DISCOVERY:-21027}
        target: 21027
    volumes:
      - type: bind
        source: ${SYNCTHING_DIR:?err}/config
        target: /var/syncthing/config
        bind:
          create_host_path: true
      - type: bind
        source: ${SYNCTHING_DIR:?err}/data
        target: /var/syncthing/data
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
