---
services:
  sshwifty:
    container_name: sshwifty
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget -q -T '2' -O /dev/null http://localhost:8182/ || exit 1
    #   timeout: 10s
    hostname: sshwifty
    image: woahbase/alpine-sshwifty:${SSHWIFTY_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${SSHWIFTY_PORT:-8182}
        target: 8182
    volumes:
      # - type: bind
      #   source: ${SSHWIFTY_DIR:?err}/configs/sshwifty.conf.json
      #   target: /config/sshwifty.conf.json
      #   bind:
      #     create_host_path: false
      # - type: bind
      #   source: ${SSHWIFTY_SSH_DIR:?err}  # or ${SSHWIFTY_DIR:?err}/ssh
      #   target: /config/ssh
      #   read_only: true
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
