---
services:
  gotify:
    container_name: gotify
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      # TZ: ${TZ}

      # only needed to initialize sqlite database
      # enable on firstrun, not needed after
      # GOTIFY_DEFAULTUSER_NAME: admin
      # GOTIFY_DEFAULTUSER_PASS: insecurebydefault
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget -q -T '2' -O /dev/null http://localhost:${GOTIFY_PORT:-80}/health || exit 1
    #   timeout: 10s
    hostname: gotify
    image: woahbase/alpine-gotify:${GOTIFY_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${GOTIFY_PORT:-80}
        target: 80
    volumes:
      - type: bind
        source: ${GOTIFY_DIR:?err}/data
        target: /gotify/data
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${GOTIFY_DIR:?err}/configs/config.yml
      #   target: /etc/gotify/config.yml
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
