---
services:
  cec:
    container_name: cec
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    devices:
      - /dev/vchiq:/dev/vchiq # for raspberry-pi
      - /dev/cec0:/dev/cec0
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # GID_DIALOUT: 984  # gid of group 'dialout'
      GID_VIDEO: 985  # gid of group 'video'
      # TZ: ${TZ}
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - >
    #       nc -z -i 1 -w 1 localhost 9526 || exit 1
    #   interval: 2m
    #   timeout: 10s
    #   retries: 5
    #   start_period: 5m
    hostname: cec
    image: woahbase/alpine-cec:${CEC_TAG:-latest}
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${CEC_PORT:-9526}
        target: 9526
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
