---
services:
  saned:
    container_name: saned
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/scanner0:/dev/scanner0
      # - /dev/usb:/dev/usb
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # SANED_CONF_abaton: "--/dev/scanner;/dev/scanner0"
      # SANED_CONF_airscan: >-
      #   devices=>\"Kyocera MFP Scanner\" = http://192.168.1.102:9095/eSCL;
      #   options=>discovery = enable;
      #   options=>model = network;
      #   blacklist=>--model = \"Xerox*\"
      # SANED_TRIM_CONFLINE: 1
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       nc -z -i 1 -w 1 localhost ${SANED_PORT:-6566} || exit 1
    #   timeout: 10s
    hostname: saned
    image: woahbase/alpine-saned:${SANED_TAG:-latest}
    network_mode: host
    ports:
      # - protocol: tcp
      #   host_ip: 0.0.0.0
      #   published: ${SANED_PORT:-6566}
      #   target: 80
      #
      # - "10000-10100:10000-10100"
    volumes:
      - type: bind
        source: ${SANED_DIR:?err}/config
        target: /etc/sane.d
        bind:
          create_host_path: false
      # - type: bind
      #   source: ${SANED_DIR:?err}/data
      #   target: /data
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
