---
services:
  registry:
    container_name: registry
    # depends_on:
    #   redis:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      REG_USER: ${WEBADMIN}
      REG_PASS: ${WEBPASSWORD}
      REGISTRY_HTTP_HOST: https://${REGISTRY}
      # REGISTRY_HTTP_TLS_CERTIFICATE: /data/auth/certificate.crt
      # REGISTRY_HTTP_TLS_KEY: /data/auth/private.key
      # REGISTRY_AUTH_HTPASSWD_PATH: /data/auth/.htpasswd_registry
      # TZ: ${TZ}
    # healthcheck:
    #   interval: 2m
    #   retries: 5
    #   start_period: 5m
    #   test:
    #     - CMD-SHELL
    #     - >
    #       wget --quiet --tries=1 --no-check-certificate --spider "http://localhost:4999/debug/health" || exit 1
    #   timeout: 10s
    hostname: registry
    image: woahbase/alpine-registry:${REGISTRY_TAG:-latest}
    network_mode: bridge
    ports:
      # - protocol: tcp  ## for debug/health
      #   host_ip: 0.0.0.0
      #   published: 4999
      #   target: 4999
      - protocol: tcp
        host_ip: 0.0.0.0
        published: ${REGISTRY_PORT:-5000}
        target: 5000
      - protocol: tcp  ## for reg
        host_ip: 0.0.0.0
        published: ${REGUI_PORT:-5001}
        target: 5001
    volumes:
      - type: bind
        source: ${REGISTRY_DIR:?err}/data
        target: /data
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${CERTIFICATE_DIR:?err}
      #   target: /data/auth
      #   bind:
      #     create_host_path: true
      # - type: bind
      #   source: ${REGISTRY_DIR:?err}/configs/config.yml
      #   target: /data/config.yml
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
