---
services:
  rsyslog:
    container_name: rsyslog
    deploy:
      # mode: global
      resources:
        limits:
          cpus: '2.00'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      # RSYSLOG_CONF: /etc/rsyslog.conf
      # LOGROTATE_CONF: /etc/logrotate.conf
      SYS_HOSTNAME: ${RSYSLOG_HOSTNAME:-rsyslog}
      # FWD_PROTOCOL: ${RSYSLOG_FWD_PROTOCOL}
      # FWD_TO_HOST: ${RSYSLOG_FWD_TO_HOST}
      # FWD_TO_PORT: ${RSYSLOG_FWD_TO_PORT}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # TZ: ${TZ}
    hostname: ${RSYSLOG_HOSTNAME:-rsyslog}
    image: woahbase/alpine-rsyslog:${RSYSLOG_TAG:-latest}
    # # example for other containers
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: udp://${RSYSLOG_FWD_TO_HOST}:${RSYSLOG_FWD_TO_PORT}
    #     tag: rsyslog
    network_mode: bridge
    ports:
      - protocol: tcp
        host_ip: 0.0.0.0
        published: 514
        target: 514
      - protocol: udp
        host_ip: 0.0.0.0
        published: 514
        target: 514
      - protocol: tcp
        host_ip: 0.0.0.0
        published: 2514
        target: 2514
    volumes:
      - type: bind
        source: ${RSYSLOG_DIR:?err}/rsyslog.conf
        target: /etc/rsyslog.conf
        bind:
          create_host_path: false
      # - type: bind
      #   source: ${RSYSLOG_DIR:?err}/rsyslog.d
      #   target: /etc/rsyslog.d
      #   bind:
      #     create_host_path: false
      - type: bind
        source: ${RSYSLOG_DIR:?err}/log
        target: /var/log
        bind:
          create_host_path: true
      - type: bind
        source: ${RSYSLOG_DIR:?err}/spool
        target: /var/spool/rsyslog
        bind:
          create_host_path: true
      # # for systemd-journald logs
      # - type: bind
      #   source: /run/systemd/journal
      #   target: /run/systemd/journal
      #   read_only: true
      #   bind:
      #     create_host_path: false
      - type: bind
        source: ${RSYSLOG_DIR:?err}/logrotate.conf
        target: /etc/logrotate.conf
        bind:
          create_host_path: false
      # - type: bind
      #   source: ${RSYSLOG_DIR:?err}/logrotate.d
      #   target: /etc/logrotate.d
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
